// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");

var emptyUsers = /* Success */Block.__(0, [/* [] */0]);

function createClient(get, connection) {
  return /* record */[/* getUsers */(function (param) {
              var url = connection[/* domain */1] + "/users";
              return Curry._2(get, url, undefined).then((function (unit) {
                            return Promise.resolve(emptyUsers);
                          }));
            })];
}

exports.emptyUsers = emptyUsers;
exports.createClient = createClient;
/* No side effect */
