// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE

import * as Client$AtlasClient2 from "./Client.bs.js";

var clientModule = {
  createClient: Client$AtlasClient2.createClient,
  createBasicAuthentication: Client$AtlasClient2.createBasicAuthentication,
  createConnection: Client$AtlasClient2.createConnection
};

var createClient = Client$AtlasClient2.createClient;

var createBasicAuthentication = Client$AtlasClient2.createBasicAuthentication;

var createConnection = Client$AtlasClient2.createConnection;

export {
  createClient ,
  createBasicAuthentication ,
  createConnection ,
  clientModule ,
  
}
/* No side effect */
