version: 0.2

env:
  variables:
    "npm_config_cache": "/tmp/npm-cache"

phases:
  install:
    commands:
      - npm ci
  build:
    commands:
      - echo Build started on `date`
      - make ci
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - dist/**/*.js
cache:
  paths:
    - ~/.npm
    - "/tmp/npm-cache"
