version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm i
  build:
    commands:
      - npm test
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - src/**/*
    - package.json
    - package-lock.json
    - Dockerfile
    - config.json
  discard-paths: no
cache:
  paths:
    - '/root/.npm'