version: 0.2

phases:
  install:
    commands:
      - npm ci
  build:
    commands:
      - echo Build started on `date`
      - make
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - dist/*
cache:
  paths:
    - "$HOME/.npm"
