version: 0.2

phases:
  install:
    commands:
      - npm ci
  build:
    commands:
      - echo Build started on `date`
      - make ci
      - bash ./ci/docker-build.sh
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - docker-temp/*
cache:
  paths:
    - ~/.npm
