version: '3'
services:
  web:
    command: ["node", "src"]
    build: .
    environment:
      CONFIG_PATH: /opts/cartographer/local.config.json
    ports:
    - "8080:80"
    volumes:
    - .:/opts/cartographer