// flow-typed signature: 771c04bccdeed0f064497b615a731386
// flow-typed version: <<STUB>>/lk-test_v^2.4.0/flow_v0.101.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lk-test'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lk-test' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lk-test/dist/lk-test.cjs' {
  declare module.exports: any;
}

declare module 'lk-test/dist/lk-test.esm' {
  declare module.exports: any;
}

declare module 'lk-test/rollup.config' {
  declare module.exports: any;
}

declare module 'lk-test/src/assertions' {
  declare module.exports: any;
}

declare module 'lk-test/src/assertions.test' {
  declare module.exports: any;
}

declare module 'lk-test/src/index' {
  declare module.exports: any;
}

declare module 'lk-test/src/index.test' {
  declare module.exports: any;
}

declare module 'lk-test/src/lib' {
  declare module.exports: any;
}

declare module 'lk-test/src/lib.test' {
  declare module.exports: any;
}

declare module 'lk-test/src/reporter' {
  declare module.exports: any;
}

declare module 'lk-test/src/reporter.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lk-test/dist/lk-test.cjs.js' {
  declare module.exports: $Exports<'lk-test/dist/lk-test.cjs'>;
}
declare module 'lk-test/dist/lk-test.esm.js' {
  declare module.exports: $Exports<'lk-test/dist/lk-test.esm'>;
}
declare module 'lk-test/rollup.config.js' {
  declare module.exports: $Exports<'lk-test/rollup.config'>;
}
declare module 'lk-test/src/assertions.js' {
  declare module.exports: $Exports<'lk-test/src/assertions'>;
}
declare module 'lk-test/src/assertions.test.js' {
  declare module.exports: $Exports<'lk-test/src/assertions.test'>;
}
declare module 'lk-test/src/index.js' {
  declare module.exports: $Exports<'lk-test/src/index'>;
}
declare module 'lk-test/src/index.test.js' {
  declare module.exports: $Exports<'lk-test/src/index.test'>;
}
declare module 'lk-test/src/lib.js' {
  declare module.exports: $Exports<'lk-test/src/lib'>;
}
declare module 'lk-test/src/lib.test.js' {
  declare module.exports: $Exports<'lk-test/src/lib.test'>;
}
declare module 'lk-test/src/reporter.js' {
  declare module.exports: $Exports<'lk-test/src/reporter'>;
}
declare module 'lk-test/src/reporter.test.js' {
  declare module.exports: $Exports<'lk-test/src/reporter.test'>;
}
