version: '2.1'
jobs:
  test:
    docker:
      - image: circleci/buildpack-deps
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: Build Dev Image
          command: docker build --target builder -t dev-container .
      - run:
          name: Test Application
          command: docker run dev-container npm run test
      - run:
          name: Type Application
          command: docker run dev-container npm run type
  publish:
    environment:
      IMAGE_NAME: astralatlas/cartographer
    docker:
      - image: circleci/buildpack-deps
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: Login with Credentials
          command: $DOCKER_PASSWORD | docker login --username=$DOCKER_USERNAME --password-stdin
      - run:
          name: Build Production Image
          command: docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$CIRCLE_TAG .
      - run:
          name: Publish Latest Image
          command: docker push $IMAGE_NAME:latest
      - run:
          name: Publish Versioned Image
          command: docker push $IMAGE_NAME:$CIRCLE_TAG
workflows:
  version: 2
  build-and-publish:
    jobs:
      - test
      - publish:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          requires:
            - test